version: '3'

services:

  proxy:
    image: traefik
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    deploy:
      restart_policy:
        condition: "on-failure"
      placement:
        constraints:
          - "node.role == manager"
      labels:
        - "traefik.enable=true"
        - "traefik.backend={{ role_path | basename }}"
        - "traefik.port=8080"
        - "traefik.docker.network={{ docker_proxy_network }}"
        - "traefik.frontend.rule=Host:{{ role_path | basename }}.{{ inventory_clustername }}"
    networks:
      - "{{ docker_proxy_network }}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/volume1/{{ inventory_hostname[4:7] | upper() }}Stack/{{ role_path | basename }}/etc/traefik:/etc/traefik"

networks:
  {{ docker_proxy_network }}:
    external: true
